# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches }: let
  src = fetchFromGitHub {
    owner = "mastodon";
    repo = "mastodon";
    rev = "v4.2.0";
    hash = "sha256-x8sPH2EPv0/j69+63+SWUgjuPqTRSs+/tkA3qlifbKI=";
  };
in applyPatches {
  inherit src;
  patches = [];
}
