# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches, fetchpatch }: let
  src = fetchgit {
    url = "https://github.com/mastodon/mastodon.git";
    rev = "v4.1.2";
    sha256 = "18yzpc2rz9sa04y2sdxzsfkndbqqsfqvji47imwc3yj40l8hciws";
  };
in applyPatches {
  inherit src;
  patches = [
    (fetchpatch {
      url = "https://github.com/mastodon/mastodon/commit/e7b81d7d9625893b1323e12215a2a98c0f19f58f.patch";
      hash = "sha256-cF0wtbjTNbsyqHb3uy5zYFaACIcziJ2ulJpOT5VoDO0=";
    })
  ];
}
